import Head from "next/head";
import Layout from "../components/Layout/Layout";
import PageTitle from "../components/PageTitle";

const About = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <PageTitle title="ABOUT US" />

        <div>
          <div className="text-center mb-4">
            Established in 2021, TFP&apos;s aim is to revolutinize the modeling
            industry by including an exquisite, diverse collection of people
            that might not always fit the industry norm for looks. We work with
            all kinds of beautiful individuals to help them see beyond what is
            on the outside.
          </div>
          <div className="text-center mb-5">
            TFP Modeling agency, established in 2021 in Cairo, is a new and
            promising agenncy ready to represrnt models in different aspects of
            the profession. We have a huge desire to revolutinize the fashion
            industry by including an exquisite, diverse collection of people
            that might not always fit the industry norm for looks.
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default About;
