import Head from "next/head";
import ApplyForm from "../components/Apply/ApplyForm";

const Apply = () => {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ApplyForm />
    </div>
  );
};

export default Apply;
