import Head from "next/head";
import { useEffect, useState } from "react";
// import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import Layout from "../components/Layout/Layout";
import PageTitle from "../components/PageTitle";
import styles from "../styles/Contact.module.scss";

const Contact = () => {
  const [inBrowser, setInBrowser] = useState(false);

  useEffect(() => {
    setInBrowser(true);
    return () => {
      setInBrowser(false);
    };
  }, []);
  const Map = () => {
    if (inBrowser) {
      var {
        Map,
        MapContainer,
        Marker,
        Popup,
        TileLayer,
      } = require("react-leaflet");
      return (
        <MapContainer
          style={{ width: "100%", height: "100%" }}
          center={[30.0935386, 31.3216129]}
          zoom={13}
          scrollWheelZoom={true}
        >
          <TileLayer
            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <Marker position={[30.0935386, 31.3216129]}>
            <Popup>
              A pretty CSS3 popup. <br /> Easily customizable.
            </Popup>
          </Marker>
        </MapContainer>
      );
    } else return null;
  };

  const ContactItem = ({ label, contacts }) => {
    return (
      <div
        style={{ borderBottom: "solid black 3px" }}
        className="d-flex my-4 justify-content-between"
      >
        <h4 className="my-auto">{label}</h4>
        <div className="mx-5">
          {contacts.map((contact, index) => (
            <div key={index} className={styles.contactEmail}>
              <a href={contact.email}>{contact.label}</a>
            </div>
          ))}
        </div>
      </div>
    );
  };
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossOrigin=""
        />
        {/* <script
          src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
          crossOrigin=""
        ></script> */}
      </Head>

      <Layout>
        <PageTitle title="CONTACT US" />

        <div>
          <ContactItem
            label="MANAGEMENT"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
          <ContactItem
            label="SCOUTING &amp; PLACEMENT"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
          <ContactItem
            label="ART DEPARTMENT"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
          <ContactItem
            label="BOOKING"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
          <ContactItem
            label="ACCOUNTING &amp; BACK OFFICE"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
          <ContactItem
            label="(FOR ANY INQUIRIES)"
            contacts={[
              { label: "SHERIF", email: "mailto:sherif@gmail.com" },
              { label: "SHADY", email: "mailto:shady@gmail.com" },
            ]}
          />
        </div>

        <div style={{ height: "500px", marginBottom: "40px" }}>
          <Map />
        </div>
      </Layout>
    </div>
  );
};

export default Contact;
