import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.scss";
import ModelImage from "../public/images/model.jpg";
import Footer from "../components/Footer/Footer";
// import HomePageVideo from "../public/videos/homeBackground.mp4";

export default function Home() {
  const homePageVideoSource =
    "https://www.youtube.com/embed/hgBfkFjF2v8?autohide=0&autoplay=1&controls=0&loop=0";

  const HomePageVideo = require("../public/videos/homeBackground.mp4");

  const AboutUs = () => {
    return (
      <div className={styles.aboutUsContainer}>
        <div className={styles.infoDiv}>
          <div className={`tfp-title ${styles.title}`}>ABOUT OUR AGENCY</div>
          <div className={styles.content}>
            TFP modeling agency, working globally on maintaining the concept of
            diversity not only in people but also in ideas and photoshoot.
          </div>
          <Link href="/about">
            <div className={`tfp-btn ${styles.aboutBtn}`}>
              SEE MORE ABOUT US
            </div>
          </Link>
        </div>
        <div className={styles.imgDiv}>
          <Image src={ModelImage} height="400px" width="320px" alt="model" />
        </div>
      </div>
    );
  };

  return (
    <div>
      <Head>
        <title>TFP Models</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout isHomePage={true}>
        <video
          autoPlay
          muted
          loop
          style={{
            position: "absolute",
            objectFit: "cover",
            width: "100vw",
            height: "420px",
            top: 0,
            left: 0,
            zIndex: -1,
          }}
        >
          <source src={HomePageVideo} type="video/mp4" />
          <source src={HomePageVideo} type="video/webm" />
        </video>
        <div className={styles.homeContainer}>
          <AboutUs />

          <Footer />
        </div>
      </Layout>
    </div>
  );
}
